### ISSUE TITLE
NPE in RedditTest#listingsFor with fresh clone of master at e9e218c

### ISSUE THREAD

**Issue by travisfw** [corydissinger/raw4j#17]
I just cloned and attempted a `mvn install` and got a failing test.
For lack of a way to attach the surefire reports, I committed them to a github clone.

https://github.com/travisfw/raw4j/tree/testfail-e9e218c/target/surefire-reports

To view, do something like (untested):

``` bash
git remote add travisfw git@github.com:travisfw/raw4j.git
git fetch travisfw
git checkout travisfw/testfail-e9e218c
firefox target/surefire-reports/Command\ line\ suite/index.html
```

**Comment by travisfw** [comment]
Btw if there were a tag for the last stable commit, or a stable branch, this wouldn't be a deal breaker, but as it is, I'm not going to sort through all the commits so I just can't use raw4j.

**Comment by corydissinger** [comment]
Thanks for the heads up, I'll spend some time tonight to see what caused your issue & make a stable branch.

Keep in mind the test cases are actually hitting the API (rather than just mocked results) so if the response JSON structure changes we know ASAP.

**Comment by corydissinger** [comment]
I've cleaned up the RedditTest integration test to avoid NPEs, allowed the test-output directory to be committed to the repo for additional proof of functionality, and tagged that commit as a stable point.

**Comment by travisfw** [comment]
Thanks I'll give it another try this weekend! I honestly thought that committing the test output directory was a hack... I'd purge that branch.
