### ISSUE TITLE
NullPointerException thrown..

### ISSUE THREAD

**Issue by ghost** [corydissinger/raw4j#19]
I am calling the method commentsFor(), as below,

moreCommentsResponse = commentsFor("MotoG","22mk0r");
            if(moreCommentsResponse.getMore().getChildren() == null){
                System.out.println("No More entries..");
            }
            else 
                System.out.println(" More entries..");

Console Output:
# "No More entries.."

There was a NULL pointer exception in the code, I added the above logs to confirm it.. 
When I check the actual data, there are children nodes, but the API fails to detect them and returns NULL..
Could you please help to suggest what could fix it..

**Comment by corydissinger** [comment]
This is a legitimate bug, good find.

I'm not sure if the reddit API has changed somewhat, or this was always broken, but the comments API has always been somewhat weird. I'll need a few more days to fix it.

**Comment by ghost** [comment]
Thanks a lot Cory...

**Comment by corydissinger** [comment]
Try the latest commits out, I believe the issue has been fixed.
